spring.application.name=Login API
# Server configuration
server.port=8080

# JWT configuration
jwt.secret=6G8sDEIJIGjgEmtEcYsAHUWKnxAAJ+H/2bkJpzxrLDq3JWxJ+0H+euNkRX5RPBvSfoaAW9MrTGo7sP1lbCI/XQ==
# 15 minutes in ms
jwt.expiration=900000
# 7 days in ms
jwt.refreshExpiration=604800000
spring.data.mongodb.uri=mongodb://localhost:27017/Logindb